mysite/converter/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path('download', views.download, name='download')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/mysite/urls.py
from django.urls import include, path
from django.contrib import admin

urlpatterns = [
    path('', include('converter.urls')),
    #path('admin/', admin.site.urls),
]

mysite/converter/models.py
from django.db import models

# Create your models here.

mysite/converter/forms.py
from django import forms

class SourceForm(forms.Form):
    html_source = forms.CharField(widget=forms.Textarea)

mysite/converter/views.py
from weasyprint import HTML
from django.shortcuts import render
from converter.forms import SourceForm
from django.views.generic.edit import FormView
from django.conf import settings
import os


# Create your views here.
class Index(FormView):
    media_path = settings.MEDIA_ROOT
    temp_file = os.path.join(media_path, 'tmp.html')
    pdf_file = os.path.join(media_path, 'output.pdf')
    template_name = 'index.html'
    form_class = SourceForm
    success_url = '/download'

    def form_valid(self, form):
        """
        checks form from forms.py and if valid will write to a file
        """
        print ('FORM IS VALID')
        # print (form.cleaned_data)
        pdf_source = form.cleaned_data['html_source']
        with open(Index.temp_file, 'w') as html_source:
            html_source.write(pdf_source)
        loaded_source = HTML(filename=Index.temp_file)
        loaded_source.write_pdf(Index.pdf_file)

        # print(loaded_source)
        return super().form_valid(form)

def download(request):
    return render(request, 'download.html', {})
    

mysite/converter/templates/download.html
<head>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
        <style>
                h1 {color:black;
                    text-align: center;
                    font-size: 60px;}
                h2 {font-size: 45px;}
               
            </style>
</head>
<div class="page-header">
<h1>Downloads</h1>
</div>
<br/>
<br/>
<h2><a href='/media/output.pdf' download>Download the PDF</a></h2>


<br/>
<h3><a href="/">Convert Again</a></h3>

mysite/converter/templates/index.html
<head>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <style>
            h1 {color:red;
                    text-align: center;}
            #id_html_source { width: 100%;
                    height: 500px;
                    padding: 50px 50px;}
            #id_html_source:focus {
                    background-color: lightblue;
}
        </style>
</head>
<div class="page-header">
<h1>HTML To PDF converter</h1>
</div>
<br/>
<br/>

<h2>Enter HTML source to convert:</h2>
<form method="POST" class "form1">{% csrf_token %}
        {{ form.as_p }}
        <button type="Convert" class="save btn btn-primary">Save</button>
</form>